language: php

php:
  - 7.1

sudo: false

install:
  - composer install --prefer-dist --optimize-autoloader --quiet
  - cp .env.travis .env
  - php artisan key:generate
  - php -v

script:
  - phpunit -c phpunit.xml --coverage-text

notifications:
  email:
    recipients:
      - timwu000@gmail.com
    on_success: always
    on_failure: always
